# Site settings
title: Artem's personal place on Internet
description: "A little bit about my work"
#baseurl: "/space-jekyll-template" # for test: remove string '/space-jekyll-template' to ''
url: "https://nameartem.github.io/"

# User settings
username: Artem Seleznev
user_title: Head of CVM Department @ Magnit
facebook_username: seleznev.artem.info
github_username:  nameartem
linkedin_public_url: seleznev-artem


# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  section_1:
    - title: home
      url: /
      key_trigger: 1
    - title: posts
      url: /posts
      key_trigger: 2
    - title: project
      url: /project
      key_trigger: 3
  section_2:
    - title: about me
      url: /about
      key_trigger: a


# projects in header index
# projects:
#  - name:
#    url:

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
